server {
    listen 80;
    server_name http://sweek.ovh;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location = /pong-ws/health {
        proxy_pass http://pong-api:3000/health;
        proxy_set_header Host $host;
        access_log off;
    }

    location /pong-ws/ {
        proxy_pass http://pong-api:3000/ws;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;

        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_buffering off;
        proxy_read_timeout 86400;
    }

    location = /tower-ws/health {
        proxy_pass http://tower-api:3001/health;
        proxy_set_header Host $host;
        access_log off;
    }

    location /tower-ws/ {
        proxy_pass http://tower-api:3001/ws;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;

        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_buffering off;
        proxy_read_timeout 86400;
    }

    location /grafana/ {
        proxy_pass http://grafana:3000; # Surtout pas de / ici

        # Transmet le Host d'origine (localhost:8080)
        proxy_set_header Host $http_host;

        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_redirect off;
    }

    location /prometheus/ {
        proxy_pass http://prometheus:9090; # On enlève le / final
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}