version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: portfolio_front
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`sweek.ovh`) || Host(`www.sweek.ovh`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"
    networks: [app-network]
    restart: always

  pong-api:
    build: ./pong
    container_name: pong_api
    networks: [app-network]
    restart: always

  tower-api:
    build: ./tower-defense
    container_name: tower_api
    networks: [app-network]
    restart: always

networks:
  app-network:
    external: true