global:
  scrape_interval: 15s # Prometheus récupère les données toutes les 15 secondes
  evaluation_interval: 15s

scrape_configs:
  # 1. Monitoring des ressources matérielles (CPU, RAM des conteneurs)
  - job_name: 'docker-infra'
    static_configs:
      - targets: ['cadvisor:8080']

  # 2. Monitoring de l'état de Prometheus lui-même
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  # 3. Monitoring de tes APIs (via leurs ports internes au réseau Docker)
  # Note : Prometheus peut interroger directement les conteneurs par leur nom
  - job_name: 'game-apis'
    metrics_path: '/health' # Il va tenter de lire pong-api:3000/health
    static_configs:
      - targets:
          - 'pong-api:3000'
          - 'tower-api:3001'